### ISSUE TITLE
Setting the background color is hard

### ISSUE THREAD

**Issue by AlexDaniel** [raydiak/Image-PNG-Portable#6]
It takes a couple of seconds to set the background color with a bunch of ``set`` calls, I think the constructor should provide an easy way of doing this.

**Comment by raydiak** [comment]
I didn't put it in the constructor, but there is now a set-all method which should serve your purposes. It was originally excluded because there was no reasonably performant way to fill a Buf, but Rakudo has made great strides in performance since then.
